name: Parallel Test Build
on: push
jobs:
  registration-of-new-users:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:registerUsers

      - name: Upload HTML Report
        if: always() # This ensures that a report is generated for all test - positive and negative
        uses: actions/upload-artifact@v4
        with:
          name: Registration-Report
          path: cypress/reports/html/

  add-to-cart:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart

      - name: Upload HTML Report
        if: always() # This ensures that a report is generated for all test - positive and negative
        uses: actions/upload-artifact@v4
        with:
          name: AddToCart-Report
          path: cypress/reports/html/
